services:
  redis:
    image: redis:7-alpine
    container_name: demo-redis
    ports:
      - "6379:6379"
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot_demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE

  app:
    image: crpi-03c6lgrb4dttid0s-vpc.cn-shanghai.personal.cr.aliyuncs.com/docker_wangyang/docker:latest
    container_name: demo-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_NAME: springboot_demo
      DB_USER: root
      DB_PASS: root
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    restart: on-failure

volumes:
  mysql_data:
